#data preprocessing:
general:
  cores: 4
  seed:    # seed for dataset subselection and random initialization
  save_metric: False

mlflow:
  tracking_uri: 'sqlite:////home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns/store.db'  
  #tracking_uri: "sqlite:////home/mila/b/benjamin.therien/github/kymatio_mod/runs_ben/mlruns/store.db" #'sqlite:////home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns/store.db'  # 'sqlite:////home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns/store.db' # '/home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns' #'/NOBACKUP/gauthiers/kymatio_mod/mlruns'
  experiment_name: 'test2'

dataset:
  name: 'cifar' # choices=['cifar', 'kth', 'x-ray']
  num_classes: 10
  train_batch_size: 100
  test_batch_size: 512
  train_sample_num: 100  #total train samples
  test_sample_num: 10000
  data_root: #'/home/gauthiers/kymatio_datasets/'
  data_folder: 'CIFAR'
  height:  32   # ultrasound image dimension
  width:  32   # ultrasound image dimension
  augment: 'autoaugment' #choices=['autoaugment','original-cifar','noaugment','glico']
  sample: 
  glico: 0
  accum_step_multiple: 128
# kymatio 

scattering:
  J: 2
  max_order: 2
  lr_scattering: 0.1
  lr_orientation: 0.1
  init_params: 'Kymatio' # 'Random' or 'Kymatio'
  learnable: False # True if learnable
  second_order: False
  architecture: 'scattering'


optim: 
  name: 'sgd' #choices=['adam', 'sgd']
  lr: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  max_lr: 0.06 #highest lr we can
  scheduler: 'OneCycleLR' #choices=['CosineAnnealingLR','OneCycleLR','LambdaLR','StepLR','NoScheduler']
  div_factor: 25 # so far, best results with 25 and maxlr = 0.05
  three_phase: False 
  phase_num:
  alternating: True
  T_max: 
  phase_ends:

model:
  name: 'linear_layer' # choices=['cnn', 'mlp', 'linear_layer']
  width: 8   # width factor for resnet
  epoch: 5
  step_test: 25
  loss: 'cross-entropy' # choices=['cross-entropy', 'cosine', 'cross-entropy-accum']
  average: False
  save: False






