#data preprocessing:
general:
  cores: 4
  seed:    # seed for dataset subselection and random initialization
  save_metric: False

mlflow:
  tracking_uri: 'sqlite:////NOBACKUP/gauthiers/kymatio_mod/mlruns_shanel/store.db' # '/home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns' #'/NOBACKUP/gauthiers/kymatio_mod/mlruns'
  experiment_name: 'xray'

dataset:
  name: 'x-ray' # choices=['cifar', 'kth', 'x-ray']
  num_classes: 2
  train_batch_size: 128
  test_batch_size: 512
  train_sample_num: 1000  #total train samples
  test_sample_num: 400
  data_root: '/NOBACKUP/gauthiers/'
  data_folder: 'chest_xrays_preprocess'
  height:  32   # ultrasound image dimension
  width:  32   # ultrasound image dimension
  augment: 'original-cifar' #choices=['autoaugment','original-cifar','noaugment','glico']
  sample: 

# kymatio 
scattering:
  J: 2
  max_order: 2
  lr_scattering: 0.1
  lr_orientation: 0.1
  init_params: 'Random' # 'Random' or 'Kymatio'
  learnable: True # True if learnable

optim: 
  name: 'sgd' #choices=['adam', 'sgd']
  lr: 0.01
  weight_decay: 0.0005
  momentum: 0.9
  max_lr: 0.07 #highest lr we can
  scheduler: 'StepLR' #choices=['CosineAnnealingLR','OneCycleLR','LambdaLR','StepLR','NoScheduler']
  div_factor: 20 # so far, best results with 25 and maxlr = 0.05
  three_phase: False 
  phase_num: 2
  alternating: True
  T_max: 

model:
  name: 'cnn' # choices=['cnn', 'mlp', 'linear_layer']
  width: 8   # widthd factor for resnet
  epoch: 1000
  step_test: 25
  



