#data preprocessing:
dimension:
  M:  32   # ultrasound image dimension
  N:  32   # ultrasound image dimension

# dataset:
#   path: '/home/gauthiers/kymatio_datasets/CIFAR'
#model
model:
  name: 'linear layer'
  architecture: 'linear_layer' # 'cnn' or 'linear_layer'
  data_root: #'/home/gauthiers/kymatio_datasets/'
  data_folder: 'CIFAR'
  lr: 0.1
  lr_scattering: 0.1
  lr_orientation: 0.1
  train_batch_size: 100
  test_batch_size: 512
  weight_decay: 0.0005
  momentum: 0.9
  seed:    # seed for dataset subselection (if None generate random)
  width: 8   # width factor for resnet
  train_sample_num: 100  #total train samples
  test_sample_num: 10000
  mode: 'scattering_dif' # network_type: choices=['scattering_dif', 'scattering', 'standard']
  epoch: 5
  optimizer: 'sgd'
  scheduler: 'OneCycleLR' # 'CosineAnnealingLR' or 'OneCycleLR' or 'LambdaLR' or 'StepLR', or 'NoScheduler'
  init_params: 'Random' # 'Random' or 'Kymatio'
  step_test: 25
  three_phase: False 
  max_lr: 0.07 #highest lr we can
  div_factor: 20 # so far, best results with 25 and maxlr = 0.05
  augment: 'autoaugment' #choices=['autoaugment','original-cifar','noaugment','glico']
  T_max: 
  comment:
  num_classes: 10
  dataset: 'cifar'

processor:
  cores: 4
  


# kymatio 
scattering:
  J: 2
  max_order: 2

mlflow:
  tracking_uri: 'sqlite:////home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns/store.db' # '/home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns' #'/NOBACKUP/gauthiers/kymatio_mod/mlruns'
  experiment_name: 'test2'
