#data preprocessing:
general:
  cores: 2
  seed: 559086261 # seed for dataset subselection and random initialization
  save_metric: False

mlflow:
  tracking_uri: 'sqlite:////NOBACKUP/gauthiers/kymatio_mod/mlruns_shanel/store.db' # '/home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns' #'/NOBACKUP/gauthiers/kymatio_mod/mlruns'
  experiment_name: 'June 7, 2021'

dataset:
  name: 'KTH' # choices=['cifar', 'kth', 'x-ray']
  num_classes: 11
  train_batch_size: 128
  test_batch_size: 128
  train_sample_num: 1188  #total train samples
  test_sample_num: 3564
  data_root: '/NOBACKUP/gauthiers/'
  data_folder: 'KTH'
  height: 128  # ultrasound image dimension
  width:  128  # ultrasound image dimension
  augment: 'original-cifar' #choices=['autoaugment','original-cifar','noaugment','glico']
  sample: 'c'
  glico: 0

# kymatio 
scattering:
  J: 4
  max_order: 2
  lr_scattering: 0.6
  lr_orientation: 0.6
  init_params: 'Kymatio' # 'Kymatio' or 'Random'
  learnable: True # True if learnable
  second_order: False
  # max_lr: 0.1
  # div_factor: 25
  # three_phase: False
 

optim: 
  name: 'sgd' #choices=['adam', 'sgd']
  lr: 0.001 
  weight_decay: 0.0005
  momentum: 0.9
  max_lr: 0.001 #highest lr we can
  scheduler: 'OneCycleLR'  #choices=['CosineAnnealingLR','OneCycleLR','LambdaLR','StepLR','NoScheduler']
  div_factor: 25 # so far, best results with 25 and maxlr = 0.05
  three_phase: False
  phase_num: 3
  alternating: False
  T_max: 
  phase_ends: #["50", "100", "200"]

model:
  name: 'cnn' # choices=['c', 'mlp', 'linear_layer']
  width: 8   # width factor for resnet
  epoch: 100
  step_test: 25
  loss: 'cross-entropy' # choices=['cross-entropy', 'cosine']
  



