#data preprocessing:
preprocess:
  dimension:
    M:  32   # ultrasound image dimension
    N:  32   # ultrasound image dimension

#model
model:
  name: 'linear layer'
  lr: 0.1
  lr_scattering: 0.1
  lr_orientation: 0.1
  batch_size: 64
  weight_decay: 0.0005
  momentum: 0.9
  seed: None    # seed for dataset subselection (if None generate random)
  width: 2   # width factor for resnet
  num_samples: 100  #total train samples
  mode: 'scattering_dif' # network_type: choices=['scattering_dif', 'scattering', 'standard']
  epoch: 6000
  optimizer: 'sgd'
  scheduler: 'OneCycleLR' # 'CosineAnnealingLR' or 'OneCycleLR' or 'LambdaLR' or 'StepLR', or 'NoScheduler'
  init_params: 'Random' # 'Random' or 'Kymatio'
  step_test: 25
  three_phase: False 
  max_lr: 0.05 #highest lr we can
  augment: 'autoaugment' #choices=['autoaugment','original-cifar','noaugment','glico']
  T_max: 
  comment: 

   
# kymatio 
scattering:
  J: 2
  max_order: 2

mlflow:
  tracking_uri: 'data_runs/mlruns'
  experiment_name: 'linear_layer_baseline_v2'

