#data preprocessing:
general:
  cores: 4
  seed:  42  # seed for dataset subselection and random initialization
  save_metric: False

mlflow:
  tracking_uri: 'sqlite:////NOBACKUP/gauthiers/kymatio_mod/mlruns_shanel/store.db'
  # tracking_uri: 'sqlite:////home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns/store.db' # '/home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns' #'/NOBACKUP/gauthiers/kymatio_mod/mlruns'
  experiment_name: 'deformation_save'

dataset:
  name: 'x-ray' # choices=['cifar', 'kth', 'x-ray']
  num_classes: 2
  train_batch_size: 128
  test_batch_size: 128
  train_sample_num: 1000  #total train samples
  test_sample_num: 400
  data_root: '/NOBACKUP/gauthiers/'
  data_folder: 'chest_xrays_preprocess'
  height:  128   # ultrasound image dimension
  width:  128  # ultrasound image dimension
  augment: 'original-cifar' #choices=['autoaugment','original-cifar','noaugment','glico']
  sample:
  glico: 0
  accum_step_multiple: 128

# kymatio 
scattering:
  J: 3
  max_order: 2
  lr_scattering: 0.1
  lr_orientation: 0.1
  init_params: 'Kymatio' # 'Random' or 'Kymatio'
  learnable: False # True if learnable
  second_order: False
  architecture: 'scattering'

optim: 
  name: 'sgd' #choices=['adam', 'sgd']
  lr: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  max_lr: 0.06 #highest lr we can
  scheduler: 'OneCycleLR' #choices=['CosineAnnealingLR','OneCycleLR','LambdaLR','StepLR','NoScheduler']
  div_factor: 25 # so far, best results with 25 and maxlr = 0.05
  three_phase: False 
  phase_num: 2
  alternating: False
  T_max: 

model:
  name: 'linear_layer' # choices=['cnn', 'mlp', 'linear_layer', 'resnet50']
  width: 8   # widthd factor for resnet
  epoch: 200
  step_test: 25
  loss: 'cross-entropy' # choices=['cross-entropy', cross-entropy-accum', 'cosine']
  average: False
  save: True

  



