#data preprocessing:
general:
  cores: 2
  seed:    # seed for dataset subselection and random initialization
  save_metric: False

mlflow:
  tracking_uri: 'sqlite:////NOBACKUP/gauthiers/kymatio_mod/mlruns_shanel/store.db' # '/home/benjamin/Documents/github/kymatio_mod/runs_ben/mlruns' #'/NOBACKUP/gauthiers/kymatio_mod/mlruns'
  experiment_name: 'KTH2- all orders'

dataset:
  name: 'KTH' # choices=['cifar', 'kth', 'x-ray']
  num_classes: 11
  train_batch_size: 128
  test_batch_size: 128
  train_sample_num: 1188  #total train samples
  test_sample_num: 3564
  data_root: '/NOBACKUP/gauthiers/'
  data_folder: 'KTH'
  height: 128  # ultrasound image dimension
  width:  128  # ultrasound image dimension
  augment: 'original-cifar' #choices=['autoaugment','original-cifar','noaugment','glico']
  sample: 'd'

# kymatio 
scattering:
  J: 2
  max_order: 2
  lr_scattering: 0.1
  lr_orientation: 0.1
  init_params: 'Random' # 'Kymatio' or 'Random'
  learnable: True # True if learnable
  second_order: False

optim: 
  name: 'sgd' #choices=['adam', 'sgd']
  lr: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  max_lr: 0.05 #highest lr we can
  scheduler: 'StepLR' #choices=['CosineAnnealingLR','OneCycleLR','LambdaLR','StepLR','NoScheduler']
  div_factor: 5 # so far, best results with 25 and maxlr = 0.05
  three_phase: False 
  phase_num: 3
  alternating: False
  T_max: 

model:
  name: 'linear_layer' # choices=['cnn', 'mlp', 'linear_layer']
  width: 8   # width factor for resnet
  epoch: 200
  step_test: 25
  



